# NOTE: Comments and docstrings were generated by AI.

import numpy as np
import matplotlib.pyplot as plt
import cv2

class PathPlanner():
    """Class to plan a path from a start point to a goal in a given image."""
    
    def __init__(self, start: list[int], goal: list[int], image: np.ndarray) -> None:
        """
        Initializes the PathPlanner with start and goal nodes, and the image.

        Parameters:
        - start: List[int] - The starting coordinates (row, column).
        - goal: List[int] - The goal coordinates (row, column).
        - image: np.ndarray - The input binary image (0 for obstacles, 1 for free space).
        """

        self.explored = []       # Nodes that have been explored
        self.nodes = []          # List of all nodes
        self.to_expand = [start] # Nodes to be expanded
        self.parent_nodes = [None]  # Parent nodes for backtracking
        self.goal = goal         # Goal node
        self.image = image       # Input image
        self.connections = dict() # Connections between nodes for backtracking

    def validate(self, node: list[int]) -> bool:
        """
        Validates whether the given node is within the boundaries of the image.

        Parameters:
        - node: List[int] - The coordinates to validate.

        Returns:
        - bool: True if the node is valid, False otherwise.
        """

        if node[0] > (self.image.shape[0] - 1) or node[0] < 0 or node[1] > (self.image.shape[1] - 1) or node[1] < 0:
            return False
        return True

    def expand(self, current: list[int]) -> bool:
        """
        Expands the current node by adding its neighbors to the list of nodes to expand.

        Parameters:
        - current: List[int] - The current coordinates.

        Returns:
        - bool: True if the goal is found, False otherwise.
        """

        self.explored.append(current)
        if current == self.goal:
            return True
        
        # Iterate through the neighboring nodes
        for row in range(current[0] - 1, current[0] + 2):
            for column in range(current[1] - 1, current[1] + 2):
                node = np.array([row, column]).tolist()
                if not self.validate(node):  # Validate the node
                    continue
                if self.image[row, column] != 0 and node not in self.explored:
                    self.to_expand.append(node)         # Add to expand list
                    self.parent_nodes.append(current)    # Track the parent node

        return False

    def select_next_node(self) -> tuple[list[int], list[int]]:
        """
        Selects the next node to expand based on the distance to the goal.

        Returns:
        - Tuple[List[int], List[int]]: The next node and its parent node.
        """

        nodes = np.array(self.to_expand)
        distances = np.linalg.norm(nodes - self.goal, axis=1)  # Calculate distances to goal
        index = np.argmin(distances)  # Find the closest node
        next_node, parent_node = self.to_expand.pop(index), self.parent_nodes.pop(index)
        return next_node, parent_node
    
    def backtrack(self) -> list[list[int]]:
        """
        Backtracks from the goal to the start node to construct the path.

        Returns:
        - List[List[int]]: The final path from start to goal.
        """

        path = []
        current_node = self.goal
        while current_node is not None:
            key = current_node[0] * self.image.shape[1] + current_node[1]
            path.append(current_node)
            current_node = self.connections.get(key, None)  # Get the parent node

        return path[::-1]  # Reverse the path to go from start to goal
    
    def plan(self) -> list[list[int]]:
        """Plans the path from the start to the goal node."""

        goal_found = False
        while not goal_found:
            if len(self.to_expand) == 0:
                return None  # Return None if no path found
            
            next_node, parent_node = self.select_next_node()
            if next_node in self.explored:
                continue  # Skip already explored nodes

            key = next_node[0] * self.image.shape[1] + next_node[1]
            self.connections[key] = parent_node  # Record connection for backtracking

            goal_found = self.expand(next_node)  # Expand the next node

        path = self.backtrack()  # Backtrack to get the path
        print(path)
        return path

def min_pool(frame: np.ndarray, kernel_size: int) -> np.ndarray:
    """
    Applies a minimum pooling operation on the given frame.

    Parameters:
    - frame: np.ndarray - The input image/frame.
    - kernel_size: int - The size of the pooling kernel.

    Returns:
    - np.ndarray: The pooled image/frame or -1 if the frame is too small.
    """

    if frame.shape[0] < kernel_size or frame.shape[1] < kernel_size:
        return -1  # Invalid kernel size
    
    result_size_col = np.ceil(frame.shape[1] / kernel_size)
    result_size_row = np.ceil(frame.shape[0] / kernel_size)
    result_arr = np.zeros((result_size_row.astype(np.int32), result_size_col.astype(np.int32)))

    # Iterate through non-overlapping blocks to find minimum
    for row_index in range(result_size_row.astype(np.int32)):
        row_start = row_index * kernel_size
        row_end = row_start + kernel_size
        for col_index in range(result_size_col.astype(np.int32)):
            col_start = col_index * kernel_size
            col_end = col_start + kernel_size
            result_arr[row_index, col_index] = np.min(frame[row_start:row_end, col_start:col_end])

    return result_arr

def read_image() -> np.ndarray:
    """Reads and preprocesses the image for path planning."""

    file = 'map.pgm'  # File containing the map
    image = cv2.imread(file, 0)  # Read the image in grayscale
    image[image < 250] = 0  # Set obstacles
    image[image != 0] = 1  # Set free space
    decomposed_image = min_pool(image, 25)  # Apply minimum pooling
    return decomposed_image


if __name__ == "__main__":
    image = read_image()  # Read and preprocess the image
    planner = PathPlanner(
        start=[2, 12],  # Starting coordinates
        goal=[11, 7],   # Goal coordinates
        image=image
    )
    path = planner.plan()  # Plan the path

    # Visualize the planned path
    plt.imshow(image, cmap='gray')
    if path is not None:
        path = np.array(path)
        plt.scatter(path[:, 1], path[:, 0])  # Plot the path
    plt.show()
